image: python:2.7

pipelines:
  branches:
    master:
      - step:
          script:
            - ./deploy.py

  custom:
    deploy:
      - step:
          script:
            - ./deploy.py

  default:
    - step:
        script:
          - pip install -U tox
          - tox
