image: themattrix/tox-base

pipelines:
  branches:
    master:
      - step:
          script:
            - tox
            - ./deploy.py

  custom:
    deploy:
      - step:
          script:
            - tox
            - ./deploy.py

  default:
    - step:
        script:
          - tox
